package sh.measure.android.attributes

internal object Attribute {
    const val THREAD_NAME = "thread_name"
    const val DEVICE_NAME_KEY = "device_name"
    const val DEVICE_MODEL_KEY = "device_model"
    const val DEVICE_MANUFACTURER_KEY = "device_manufacturer"
    const val DEVICE_TYPE_KEY = "device_type"
    const val DEVICE_IS_FOLDABLE_KEY = "device_is_foldable"
    const val DEVICE_IS_PHYSICAL_KEY = "device_is_physical"
    const val DEVICE_DENSITY_DPI_KEY = "device_density_dpi"
    const val DEVICE_WIDTH_PX_KEY = "device_width_px"
    const val DEVICE_HEIGHT_PX_KEY = "device_height_px"
    const val DEVICE_DENSITY_KEY = "device_density"
    const val DEVICE_LOCALE_KEY = "device_locale"
    const val OS_NAME_KEY = "os_name"
    const val OS_VERSION_KEY = "os_version"
    const val OS_PAGE_SIZE = "os_page_size"
    const val PLATFORM_KEY = "platform"
    const val NETWORK_TYPE_KEY = "network_type"
    const val NETWORK_GENERATION_KEY = "network_generation"
    const val NETWORK_PROVIDER_KEY = "network_provider"
    const val INSTALLATION_ID_KEY = "installation_id"
    const val USER_ID_KEY = "user_id"
}

internal object SpanConstant {
    const val APP_STARTUP: String = "app_startup"
    const val GESTURE_TYPE = "gesture_type"
    const val GESTURE_TARGET_ID = "gesture_target_id"
    const val GESTURE_TARGET_NAME = "gesture_target_name"
    const val LAUNCH_TYPE = "launch_type"
    const val COLD_LAUNCH_TTID = "cold_launch_ttid"
    const val WARM_LAUNCH_TTID = "warm_launch_ttid"
    const val HOT_LAUNCH_TTID = "hot_launch_ttid"
    const val COLD_LAUNCH_TTFI = "cold_launch_ttfi"
    const val WARM_LAUNCH_TTFI = "warm_launch_ttfi"
    const val HOT_LAUNCH_TTFI = "hot_launch_ttfi"
    const val CURRENT_ACTIVITY = "current_activity"
    const val ACTIVITY_TRANSITION = "activity_transition"
    const val CURRENT_SCREEN_NAME = "current_screen"
    const val PREVIOUS_SCREEN_NAME = "previous_screen"
}
